language: smalltalk
sudo: required

os:
- linux

matrix:
  include:
    - smalltalk: Pharo-7.0
      smalltalk_config: .smalltalk.ston
    - smalltalk: Pharo-6.1
      smalltalk_config: .smalltalk.ston
    - smalltalk: Pharo-5.0
      smalltalk_config: .smalltalk.ston
    - smalltalk: Pharo-4.0
      smalltalk_config: .smalltalk-legacy.ston
